"""initial schema

Revision ID: 7e95746eee84
Revises: 
Create Date: 2026-06-01 05:58:52.807728
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7e95746eee84'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('draft_name', sa.String(length=256), nullable=False),
    sa.Column('current_version', sa.String(length=16), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('working_group', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('rfc_number', sa.String(length=32), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datatracker_url', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('draft_name')
    )
    op.create_index(op.f('ix_drafts_working_group'), 'drafts', ['working_group'], unique=False)
    op.create_table('processing_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.Enum('ingestion', 'prefilter', 'draft_sync', 'summarization', 'categorization', name='processing_stage'), nullable=False),
    sa.Column('working_group', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_log_created_at'), 'processing_log', ['created_at'], unique=False)
    op.create_index('ix_processing_log_stage_date', 'processing_log', ['stage', 'created_at'], unique=False)
    op.create_table('threads',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('working_group', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'concluded', 'abandoned', name='thread_status'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consensus_state', sa.Enum('clear_consensus', 'emerging_consensus', 'active_debate', 'no_consensus', 'single_voice', name='consensus_state'), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_admin_only', sa.Boolean(), nullable=False),
    sa.Column('summary_source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('last_processed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(subject,'') || ' ' || coalesce(summary,''))", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_threads_last_activity_date'), 'threads', ['last_activity_date'], unique=False)
    op.create_index('ix_threads_search_vector', 'threads', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_threads_subject'), 'threads', ['subject'], unique=False)
    op.create_index('ix_threads_wg_last_activity', 'threads', ['working_group', 'last_activity_date'], unique=False)
    op.create_index(op.f('ix_threads_working_group'), 'threads', ['working_group'], unique=False)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='user_role'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('working_group', sa.String(length=64), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('from_name', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_url', sa.Text(), nullable=True),
    sa.Column('body_cleaned', sa.Text(), nullable=True),
    sa.Column('body_original', sa.Text(), nullable=True),
    sa.Column('in_reply_to', sa.String(length=512), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_from_address'), 'messages', ['from_address'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_messages_working_group'), 'messages', ['working_group'], unique=False)
    op.create_table('thread_drafts',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('draft_name', sa.String(length=256), nullable=False),
    sa.Column('versions_referenced', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_referenced_in_thread', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_name'], ['drafts.draft_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'draft_name')
    )
    op.create_index(op.f('ix_thread_drafts_draft_name'), 'thread_drafts', ['draft_name'], unique=False)
    op.create_table('thread_topics',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'topic_id')
    )
    op.create_index(op.f('ix_thread_topics_topic_id'), 'thread_topics', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_topics_topic_id'), table_name='thread_topics')
    op.drop_table('thread_topics')
    op.drop_index(op.f('ix_thread_drafts_draft_name'), table_name='thread_drafts')
    op.drop_table('thread_drafts')
    op.drop_index(op.f('ix_messages_working_group'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_address'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('invites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_threads_working_group'), table_name='threads')
    op.drop_index('ix_threads_wg_last_activity', table_name='threads')
    op.drop_index(op.f('ix_threads_subject'), table_name='threads')
    op.drop_index('ix_threads_search_vector', table_name='threads', postgresql_using='gin')
    op.drop_index(op.f('ix_threads_last_activity_date'), table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_processing_log_stage_date', table_name='processing_log')
    op.drop_index(op.f('ix_processing_log_created_at'), table_name='processing_log')
    op.drop_table('processing_log')
    op.drop_index(op.f('ix_drafts_working_group'), table_name='drafts')
    op.drop_table('drafts')
    # ### end Alembic commands ###
    # Postgres ENUM types are not dropped by drop_table; drop them explicitly so
    # a downgrade fully reverses the upgrade and a subsequent upgrade succeeds.
    bind = op.get_bind()
    for enum_name in (
        "thread_status",
        "consensus_state",
        "processing_stage",
        "user_role",
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
