"""initial schema

Revision ID: cdcacf370e4d
Revises:
Create Date: 2026-03-18 15:22:58.309600

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdcacf370e4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remote_url', sa.String(length=500), nullable=True),
    sa.Column('github_repo_slug', sa.String(length=200), nullable=True),
    sa.Column('git_repo_path', sa.String(length=500), nullable=False),
    sa.Column('auto_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('blocking_pr_url', sa.String(length=500), nullable=True),
    sa.Column('blocking_pr_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artifact_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('artifact_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['artifact_comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('artifact_type', sa.Enum(
        'PROJECT_DOC', 'SYSTEM_REQUIREMENTS',
        'SYSTEM_ARCHITECTURE', 'HIGH_LEVEL_PLAN',
        'COMPONENT_MAP', 'COMPONENT_REQUIREMENTS',
        'COMPONENT_ARCHITECTURE', 'COMPONENT_PLAN',
        'SUB_COMPONENT_MAP', 'SUB_COMPONENT_REQUIREMENTS',
        'SUB_COMPONENT_ARCHITECTURE', 'SUB_COMPONENT_PLAN',
        'CODE', 'CODE_REVIEW',
        name='artifacttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('component_key', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum(
        'PENDING', 'GENERATING', 'AI_REVIEWING',
        'AWAITING_REVIEW', 'APPROVED', 'REJECTED', 'STALE',
        name='artifactstatus'), nullable=False),
    sa.Column('git_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ai_review_feedback', sa.JSON(), nullable=True),
    sa.Column('human_review_notes', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_key', sa.String(length=100), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('invite_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('pipeline_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.Enum('GATED', 'ASYNC', name='executionmode'), nullable=False),
    sa.Column('default_model', sa.String(length=100), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('review_prompt_overrides', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum(
        'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED',
        'CANCELLED', name='pipelinerunstatus'),
        nullable=False),
    sa.Column('human_review', sa.Boolean(), nullable=False),
    sa.Column('ai_loops', sa.Integer(), nullable=False),
    sa.Column('stop_point', sa.Enum(
        'AFTER_ALL', 'BEFORE_CODE', 'AT_FAN_OUT',
        'AFTER_TRIPLETS', name='stoppoint'),
        nullable=False),
    sa.Column('git_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('artifact_dependencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('upstream_artifact_id', sa.String(), nullable=False),
    sa.Column('downstream_artifact_id', sa.String(), nullable=False),
    sa.Column('stage_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['downstream_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['upstream_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_config_id', sa.String(), nullable=False),
    sa.Column('stage_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('output_artifact_type', sa.String(length=100), nullable=False),
    sa.Column('input_stage_keys', sa.JSON(), nullable=False),
    sa.Column('fan_out_strategy', sa.Enum(
        'NONE', 'COMPONENT', 'SUB_COMPONENT', 'LEAF',
        name='fanoutstrategy'), nullable=False),
    sa.Column('fan_out_source_field', sa.String(length=100), nullable=True),
    sa.Column('ai_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('human_review_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_override', sa.String(length=100), nullable=True),
    sa.Column('temperature_override', sa.Float(), nullable=True),
    sa.Column('prompt_template_key', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_config_id'], ['pipeline_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('stage_key', sa.String(length=100), nullable=False),
    sa.Column('component_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum(
        'PENDING', 'RUNNING', 'AI_REVIEW',
        'AWAITING_REVIEW', 'APPROVED', 'REJECTED',
        'SKIPPED', 'FAILED', name='stagestatus'),
        nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('langgraph_thread_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage_definition_id', sa.String(), nullable=False),
    sa.Column('system_message', sa.Text(), nullable=False),
    sa.Column('output_format_instructions', sa.Text(), nullable=False),
    sa.Column('context_template', sa.Text(), nullable=False),
    sa.Column('revision_instructions', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage_definition_id'], ['stage_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_definition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_configs')
    op.drop_table('stage_executions')
    op.drop_table('stage_definitions')
    op.drop_table('artifact_dependencies')
    op.drop_table('pipeline_runs')
    op.drop_table('pipeline_configs')
    op.drop_table('invite_links')
    op.drop_table('github_credentials')
    op.drop_table('component_definitions')
    op.drop_table('artifacts')
    op.drop_table('artifact_comments')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
