DEFAULT_STAGES = [
    # ── Phase 1: Project-Level Documents (no fan-out) ──
    {
        "stage_key": "system_requirements",
        "display_name": "System Requirements",
        "order_index": 0,
        "output_artifact_type": "system_requirements",
        "input_stage_keys": [],
        "fan_out_strategy": "none",
        "prompt_template_key": "system_requirements",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "system_architecture",
        "display_name": "System Architecture",
        "order_index": 1,
        "output_artifact_type": "system_architecture",
        "input_stage_keys": ["system_requirements"],
        "fan_out_strategy": "none",
        "prompt_template_key": "architecture",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    # ── Phase 2: Component Extraction (no fan-out) ──
    {
        "stage_key": "extract_components",
        "display_name": "Component Extraction",
        "order_index": 2,
        "output_artifact_type": "component_map",
        "input_stage_keys": ["system_requirements", "system_architecture"],
        "fan_out_strategy": "none",
        "prompt_template_key": "extract_components",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    # ── Phase 3: Component-Level Architecture (fan-out per component) ──
    {
        "stage_key": "component_architectures",
        "display_name": "Component Architectures",
        "order_index": 3,
        "output_artifact_type": "component_architecture",
        "input_stage_keys": ["extract_components", "system_requirements", "system_architecture"],
        "fan_out_strategy": "component",
        "prompt_template_key": "component_arch",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    # ── Phase 4: Sub-Component Extraction (fan-out per component) ──
    {
        "stage_key": "extract_sub_components",
        "display_name": "Sub-Component Extraction",
        "order_index": 4,
        "output_artifact_type": "sub_component_map",
        "input_stage_keys": ["component_architectures", "system_requirements"],
        "fan_out_strategy": "component",
        "prompt_template_key": "extract_sub_components",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    # ── Phase 5: Component Plans (fan-out per component, LEAF ONLY) ──
    # Only runs for components that produced NO sub-components.
    # Components with sub-components are planned at the sub-component level.
    {
        "stage_key": "component_plans",
        "display_name": "Component Plans",
        "order_index": 5,
        "output_artifact_type": "component_plan",
        "input_stage_keys": [
            "component_architectures",
            "system_requirements",
            "extract_components",
        ],
        "fan_out_strategy": "component",
        "prompt_template_key": "component_plan",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    # ── Phase 6: Sub-Component Documents (fan-out per sub-component) ──
    {
        "stage_key": "sub_component_architectures",
        "display_name": "Sub-Component Architectures",
        "order_index": 6,
        "output_artifact_type": "sub_component_architecture",
        "input_stage_keys": ["extract_sub_components", "component_architectures", "system_requirements"],
        "fan_out_strategy": "sub_component",
        "prompt_template_key": "sub_component_arch",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "sub_component_plans",
        "display_name": "Sub-Component Plans",
        "order_index": 7,
        "output_artifact_type": "sub_component_plan",
        "input_stage_keys": ["sub_component_architectures", "component_architectures"],
        "fan_out_strategy": "sub_component",
        "prompt_template_key": "sub_component_plan",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    # ── Phase 7: Implementation (fan-out per leaf entity) ──
    {
        "stage_key": "code_generation",
        "display_name": "Code Generation",
        "order_index": 8,
        "output_artifact_type": "code",
        "input_stage_keys": [
            "component_plans",
            "component_architectures",
            "sub_component_plans",
            "sub_component_architectures",
        ],
        "fan_out_strategy": "leaf",
        "prompt_template_key": "codegen",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "code_review",
        "display_name": "Code Review & Fix",
        "order_index": 9,
        "output_artifact_type": "code_review",
        "input_stage_keys": [
            "code_generation",
            "component_plans",
            "component_architectures",
            "sub_component_plans",
            "sub_component_architectures",
        ],
        "fan_out_strategy": "leaf",
        "prompt_template_key": "code_review",
        "ai_review_enabled": False,
        "human_review_enabled": True,
    },
]
