DEFAULT_STAGES = [
    {
        "stage_key": "system_requirements",
        "display_name": "System Requirements",
        "order_index": 0,
        "output_artifact_type": "system_requirements",
        "input_stage_keys": [],
        "fan_out_strategy": "none",
        "prompt_template_key": "system_requirements",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "system_architecture",
        "display_name": "System Architecture",
        "order_index": 1,
        "output_artifact_type": "system_architecture",
        "input_stage_keys": ["system_requirements"],
        "fan_out_strategy": "none",
        "prompt_template_key": "architecture",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "component_requirements",
        "display_name": "Component Requirements",
        "order_index": 2,
        "output_artifact_type": "component_requirements",
        "input_stage_keys": ["system_architecture", "system_requirements"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "component_requirements",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "component_architectures",
        "display_name": "Component Architectures",
        "order_index": 3,
        "output_artifact_type": "component_architecture",
        "input_stage_keys": ["component_requirements", "system_architecture"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "component_arch",
        "model_override": "claude-opus-4-20250514",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "high_level_plan",
        "display_name": "High Level Plan",
        "order_index": 4,
        "output_artifact_type": "high_level_plan",
        "input_stage_keys": ["system_architecture", "component_architectures"],
        "fan_out_strategy": "none",
        "prompt_template_key": "high_level_plan",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "component_plans",
        "display_name": "Component Plans",
        "order_index": 5,
        "output_artifact_type": "component_plan",
        "input_stage_keys": ["component_architectures", "high_level_plan"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "component_plan",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "code_generation",
        "display_name": "Code Generation",
        "order_index": 6,
        "output_artifact_type": "code",
        "input_stage_keys": ["component_plans", "component_architectures"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "codegen",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "code_review",
        "display_name": "Code Review & Fix",
        "order_index": 7,
        "output_artifact_type": "code_review",
        "input_stage_keys": ["code_generation", "component_plans", "component_architectures"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "code_review",
        "ai_review_enabled": False,
        "human_review_enabled": True,
    },
]
