DEFAULT_STAGES = [
    {
        "stage_key": "system_architecture",
        "display_name": "High Level Architecture",
        "order_index": 0,
        "output_artifact_type": "system_architecture",
        "input_stage_keys": [],
        "fan_out_strategy": "none",
        "prompt_template_key": "architecture",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "component_architectures",
        "display_name": "Component Architectures",
        "order_index": 1,
        "output_artifact_type": "component_architecture",
        "input_stage_keys": ["system_architecture"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "component_arch",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "high_level_plan",
        "display_name": "High Level Plan",
        "order_index": 2,
        "output_artifact_type": "high_level_plan",
        "input_stage_keys": ["system_architecture", "component_architectures"],
        "fan_out_strategy": "none",
        "prompt_template_key": "high_level_plan",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "component_plans",
        "display_name": "Component Plans",
        "order_index": 3,
        "output_artifact_type": "component_plan",
        "input_stage_keys": ["component_architectures", "high_level_plan"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "component_plan",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
    {
        "stage_key": "code_generation",
        "display_name": "Code Generation",
        "order_index": 4,
        "output_artifact_type": "code",
        "input_stage_keys": ["component_plans", "component_architectures"],
        "fan_out_strategy": "component",
        "fan_out_source_field": "components",
        "prompt_template_key": "codegen",
        "ai_review_enabled": True,
        "human_review_enabled": True,
    },
]
